-
  name: install pre
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: install pre app
      apt: 
        name: 
          - vim 
          - gnome-tweak-tool
          - terminator
          - git
          

    - name: install VSCode
      snap:
        name: code
        classic: yes

    - name: install VLC
      snap:
        name: vlc
